title: Chenyi Luo
url: "https://chenyi-luo.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Research"
   link: "research"
 - name: "CV"
   link: "cv.pdf"
 - name: "Contact"
   link: "contact"
